orderService:
  image: 160631388404.dkr.ecr.eu-north-1.amazonaws.com/shopflow/order-service
  tag: cebaaacc93865ac70163b78a9f7df8824fcb4ac3
  port: 5000
  replicas: 1

inventoryService:
  image: 160631388404.dkr.ecr.eu-north-1.amazonaws.com/shopflow/inventory-service
  tag: cebaaacc93865ac70163b78a9f7df8824fcb4ac3
  port: 3000
  replicas: 1

notificationService:
  image: 160631388404.dkr.ecr.eu-north-1.amazonaws.com/shopflow/notification-service
  tag: cebaaacc93865ac70163b78a9f7df8824fcb4ac3
  port: 8080
  replicas: 1
